import { db, type Plant } from './database';
import { GameService } from '../services/gameService';

export async function seedIfEmpty() {
  const plantCount = await db.plants.count();
  if (plantCount > 0) return; // already has data
  
  // Seed demo plants
  const userId = GameService.getUserId();
  const demoPlants: Plant[] = [
    {
      id: crypto.randomUUID(),
      userId,
      name: 'Misty the Monstera',
      species: 'Monstera deliciosa',
      acquiredAt: new Date('2025-10-12'),
      soilType: 'loamy',
      soilPh: 6.5,
      potSize: '12 inch',
      potMaterial: 'terracotta',
      location: 'Living Room, South Window',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '08:00',
      baselineSignature: null,
      guardianScore: 92,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Fred the Fern',
      species: 'Nephrolepis exaltata',
      acquiredAt: new Date('2026-03-20'),
      soilType: 'peaty',
      soilPh: 6.0,
      potSize: '10 inch',
      potMaterial: 'plastic',
      location: 'Bathroom Window',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '09:00',
      baselineSignature: null,
      guardianScore: 64,
      status: 'Watching',
      photoUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Pete the Pothos',
      species: 'Epipremnum aureum',
      acquiredAt: new Date('2026-01-15'),
      soilType: 'loamy',
      soilPh: 6.2,
      potSize: '8 inch',
      potMaterial: 'ceramic',
      location: 'Office Desk',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '10:00',
      baselineSignature: null,
      guardianScore: 88,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Sadie the Snake',
      species: 'Sansevieria trifasciata',
      acquiredAt: new Date('2025-12-01'),
      soilType: 'sandy',
      soilPh: 7.0,
      potSize: '10 inch',
      potMaterial: 'terracotta',
      location: 'Bedroom Corner',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '07:30',
      baselineSignature: null,
      guardianScore: 95,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Oliver the Orbifolia',
      species: 'Calathea orbifolia',
      acquiredAt: new Date('2026-02-10'),
      soilType: 'moisture-retentive',
      soilPh: 6.5,
      potSize: '8 inch',
      potMaterial: 'plastic',
      location: 'Humid Bathroom',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '09:30',
      baselineSignature: null,
      guardianScore: 72,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Lily the Peace Lily',
      species: 'Spathiphyllum',
      acquiredAt: new Date('2025-11-20'),
      soilType: 'moisture-retentive',
      soilPh: 6.0,
      potSize: '10 inch',
      potMaterial: 'ceramic',
      location: 'Low Light Hallway',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '08:00',
      baselineSignature: null,
      guardianScore: 85,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1545241047-6083a3684587?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Ziggy the ZZ',
      species: 'Zamioculcas zamiifolia',
      acquiredAt: new Date('2025-08-05'),
      soilType: 'well-draining',
      soilPh: 6.5,
      potSize: '12 inch',
      potMaterial: 'terracotta',
      location: 'Dimly Lit Office',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '11:00',
      baselineSignature: null,
      guardianScore: 98,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Birdie the Bird of Paradise',
      species: 'Strelitzia nicolai',
      acquiredAt: new Date('2025-05-12'),
      soilType: 'well-draining',
      soilPh: 6.8,
      potSize: '16 inch',
      potMaterial: 'plastic',
      location: 'Sunny Balcony',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '07:00',
      baselineSignature: null,
      guardianScore: 90,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Sam the Spider',
      species: 'Chlorophytum comosum',
      acquiredAt: new Date('2025-09-15'),
      soilType: 'well-draining',
      soilPh: 6.5,
      potSize: '8 inch',
      potMaterial: 'ceramic',
      location: 'Hanging Basket',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '09:00',
      baselineSignature: null,
      guardianScore: 90,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Ruby the Rubber',
      species: 'Ficus elastica',
      acquiredAt: new Date('2025-10-22'),
      soilType: 'well-draining',
      soilPh: 6.2,
      potSize: '12 inch',
      potMaterial: 'terracotta',
      location: 'Entryway',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '08:30',
      baselineSignature: null,
      guardianScore: 82,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1580133318324-f2f76d987dd8?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Fiona the Fig',
      species: 'Ficus lyrata',
      acquiredAt: new Date('2026-04-01'),
      soilType: 'well-draining',
      soilPh: 6.0,
      potSize: '14 inch',
      potMaterial: 'ceramic',
      location: 'Living Room Corner',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '09:00',
      baselineSignature: null,
      guardianScore: 68,
      status: 'Watching',
      photoUrl: 'https://images.unsplash.com/photo-1580133318324-f2f76d987dd8?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Penny the Peperomia',
      species: 'Peperomia obtusifolia',
      acquiredAt: new Date('2026-03-30'),
      soilType: 'well-draining',
      soilPh: 6.5,
      potSize: '6 inch',
      potMaterial: 'plastic',
      location: 'Kitchen Window',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '10:00',
      baselineSignature: null,
      guardianScore: 94,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Cooper the Calathea',
      species: 'Maranta leuconeura',
      acquiredAt: new Date('2026-01-10'),
      soilType: 'moisture-retentive',
      soilPh: 6.0,
      potSize: '8 inch',
      potMaterial: 'ceramic',
      location: 'Bathroom Shelf',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '08:45',
      baselineSignature: null,
      guardianScore: 75,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Ava the Alocasia',
      species: 'Alocasia amazonica',
      acquiredAt: new Date('2026-02-28'),
      soilType: 'well-draining',
      soilPh: 6.2,
      potSize: '10 inch',
      potMaterial: 'plastic',
      location: 'Plant Stand',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '09:15',
      baselineSignature: null,
      guardianScore: 62,
      status: 'Alert',
      photoUrl: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'ZZ Top',
      species: 'Zamioculcas zamiifolia',
      acquiredAt: new Date('2025-07-20'),
      soilType: 'well-draining',
      soilPh: 6.5,
      potSize: '10 inch',
      potMaterial: 'plastic',
      location: 'Hallway',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '12:00',
      baselineSignature: null,
      guardianScore: 99,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Money Tree',
      species: 'Pilea peperomioides',
      acquiredAt: new Date('2026-05-01'),
      soilType: 'well-draining',
      soilPh: 6.5,
      potSize: '8 inch',
      potMaterial: 'ceramic',
      location: 'Kitchen Counter',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '08:00',
      baselineSignature: null,
      guardianScore: 88,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Draco',
      species: 'Dracaena marginata',
      acquiredAt: new Date('2025-11-11'),
      soilType: 'well-draining',
      soilPh: 6.3,
      potSize: '12 inch',
      potMaterial: 'terracotta',
      location: 'Living Room Corner',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '09:00',
      baselineSignature: null,
      guardianScore: 84,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Polka',
      species: 'Begonia maculata',
      acquiredAt: new Date('2026-04-15'),
      soilType: 'well-draining',
      soilPh: 6.0,
      potSize: '8 inch',
      potMaterial: 'plastic',
      location: 'Window Sill',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '08:30',
      baselineSignature: null,
      guardianScore: 78,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1545241047-6083a3684587?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Yara Yucca',
      species: 'Yucca elephantipes',
      acquiredAt: new Date('2025-06-30'),
      soilType: 'sandy',
      soilPh: 7.2,
      potSize: '14 inch',
      potMaterial: 'plastic',
      location: 'Deck',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '06:00',
      baselineSignature: null,
      guardianScore: 92,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1545241047-6083a3684587?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Scheff',
      species: 'Schefflera arboricola',
      acquiredAt: new Date('2025-09-01'),
      soilType: 'well-draining',
      soilPh: 6.5,
      potSize: '12 inch',
      potMaterial: 'ceramic',
      location: 'Office',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '10:00',
      baselineSignature: null,
      guardianScore: 86,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1580133318324-f2f76d987dd8?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Hearty',
      species: 'Philodendron hederaceum',
      acquiredAt: new Date('2026-02-14'),
      soilType: 'well-draining',
      soilPh: 6.0,
      potSize: '8 inch',
      potMaterial: 'plastic',
      location: 'Bookshelf',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '09:00',
      baselineSignature: null,
      guardianScore: 91,
      status: 'Stable',
      photoUrl: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: crypto.randomUUID(),
      name: 'Amazon',
      species: 'Alocasia amazonica',
      acquiredAt: new Date('2026-01-20'),
      soilType: 'well-draining',
      soilPh: 6.2,
      potSize: '10 inch',
      potMaterial: 'plastic',
      location: 'Greenhouse',
      latitude: null,
      longitude: null,
      hardinessZone: null,
      checkInTime: '08:00',
      baselineSignature: null,
      guardianScore: 55,
      status: 'Alert',
      photoUrl: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=800&auto=format&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ];
  
  for (const plant of demoPlants) {
    if (!plant.userId) plant.userId = userId;
    await db.plants.add(plant);
    await GameService.generateCardForPlant(plant.id);
    
    // Seed 7 historical check-ins for each plant
    const baseDate = new Date();
    baseDate.setDate(baseDate.getDate() - 7);
    
    for (let i = 0; i < 7; i++) {
      const checkInDate = new Date(baseDate);
      checkInDate.setDate(checkInDate.getDate() + i);
      
      await db.checkins.add({
        id: crypto.randomUUID(),
        plantId: plant.id,
        timestamp: checkInDate,
        soilMoisture: ['Moist', 'Moist', 'Dry', 'Moist', 'Wet', 'Moist', 'Moist'][i] as any,
        lightLevel: ['Indirect', 'Indirect', 'Indirect', 'Low', 'Low', 'Indirect', 'Indirect'][i] as any,
        changes: ['none'],
        photoBlob: null,
        photoUrl: null,
        signature: null,
        guardianScore: 75 + Math.floor(Math.random() * 15),
        driftScore: null,
        driftStatus: null,
        weatherTemp: 22,
        weatherHumidity: 60,
        weatherDescription: 'clear sky',
        synced: 1
      });
    }
  }

  // Add one active alert
  const monster = await db.plants.where('species').equals('Monstera deliciosa').first();
  if (monster) {
    await db.predictions.add({
      id: crypto.randomUUID(),
      plantId: monster.id,
      predictedAt: new Date(),
      riskScore: 73,
      primaryStressor: 'Humidity',
      confidence: 85,
      reasoning: ['Humidity dropped below 40% for 3 consecutive days.'],
      triggeredAlert: 1,
      alertSentAt: new Date(),
      outcome: 'pending',
      outcomeRecordedAt: null,
      modelVersion: 'rule-engine-v1'
    });
  }
}

export async function runDbMigration() {
  try {
    const { isBrokenUrl, getPlantPhoto } = await import('../utils/plantImage');
    const plants = await db.plants.toArray();
    for (const plant of plants) {
      if (isBrokenUrl(plant.photoUrl)) {
        const correctPhoto = getPlantPhoto(null, plant.species);
        await db.plants.update(plant.id, { photoUrl: correctPhoto });
      }
    }
  } catch (err) {
    console.error('Failed to run database migration:', err);
  }
}
