import React from 'react';
import { ScrollText } from 'lucide-react';
import PageWrapper from '../components/home/PageWrapper';

export default function Terms() {
  return (
    <PageWrapper className="min-h-screen px-4 sm:px-6 md:px-10 py-12">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center gap-3 mb-2">
          <ScrollText size={28} className="text-moss" />
          <h1 className="font-serif text-4xl font-bold text-text-bark">Terms of Service</h1>
        </div>
        <p className="text-xs uppercase tracking-widest text-text-stone mb-8">Last updated: September 2026 · PhytoDoctor AI</p>

        <div className="space-y-6 text-sm leading-relaxed text-text-stone font-sans">
          <section>
            <h2 className="font-serif text-xl font-bold text-text-bark mb-2">1. Acceptance</h2>
            <p>
              By using PhytoDoctor AI you agree to these terms. If you do not agree, please do not use the app.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-text-bark mb-2">2. AI diagnoses are estimates</h2>
            <p>
              Plant diagnoses, treatment plans, and survivability scores are generated by an AI model from a photo and
              the details you provide. They are <strong>educated estimates, not guarantees</strong>, and are not a
              substitute for a qualified horticulturist, arborist, or plant pathologist. Never apply a treatment you
              believe is unsafe for your plant, household, or region.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-text-bark mb-2">3. Seeds and the Garden Market</h2>
            <p>
              Seeds are a virtual reward with no monetary value, no cash-out, and no transferability. Seed discounts
              recorded in the Market are in-app records of the discount you unlocked; actual purchases and payments are
              handled entirely by Amazon under Amazon's terms. We may adjust seed earning rates, prices, or stall
              inventory at any time to keep the economy healthy.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-text-bark mb-2">4. Acceptable use</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Upload only photos you have the right to share.</li>
              <li>Do not attempt to abuse, overload, or automate access to the AI endpoints.</li>
              <li>Do not use the botanist chat for anything unrelated to plant care; it is scoped to botany by design.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-text-bark mb-2">5. Accounts</h2>
            <p>
              If local sign-in is used, credentials never leave your device — you are responsible for them. If Supabase
              sign-in is enabled, accounts are governed by Supabase authentication. We may suspend accounts that abuse
              the service.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-text-bark mb-2">6. No warranty; limitation of liability</h2>
            <p>
              The service is provided "as is" without warranties of any kind. To the maximum extent permitted by law,
              PhytoDoctor AI is not liable for any plant loss, crop loss, or damages arising from use of the app or
              reliance on AI-generated advice.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-text-bark mb-2">7. Changes</h2>
            <p>
              We may update these terms as the app evolves; material changes will be reflected in the "last updated"
              date above. Continued use constitutes acceptance. Questions: <span className="text-text-bark font-bold">terms@phytodoctor.app</span>.
            </p>
          </section>
        </div>
      </div>
    </PageWrapper>
  );
}
